### ISSUE TITLE
Add the ability to set members as attributes of the root element. (Without using [XMLAttribute])

### ISSUE THREAD

**Issue by MartiUK** [mikeobrien/Bender#38]
For reasons I won't get into, I cannot reference System.Xml and so I cannot use XMLAttributeAttributes on the object I want to serialize into xml.

Right now I'm using the following:

```C#
Serialize.Xml(mc, x => x.ExcludeMembersWhen((t, o) => t.Name == "Service" || t.Name == "Method") // Remove Service and Method elements
.Serialization(y => y.AddXmlVisitor(
(source, target, options) => target.Element.Add(new XAttribute("service", mc.Service), new XAttribute("method", mc.Method)), // Add them as attributes
(source, target, options) => source.Name == "methodCall"))); // on the methodCall element (the root element).
```
(If I'm doing something absolutely wrong here let me know!)

Instead something like this: 
```C#
Serialize.Xml(mc, x => x.MembersAsRootAttributes((t, o) => t.Name == "Service" || t.Name == "Method"))
```
Would be pretty cool.

**Comment by mikeobrien** [comment]
Yeah, I think this is doable. Can you give me a snippet of the type you are trying to serialize and the desired XML output? I'll see if there is a way to pull it off with the current api (along the lines of what you're looking for) or that doesn't work, try to add support for it.

**Comment by MartiUK** [comment]
```C#
public class MethodCall
{
    public MethodCall(string service, string method, Dictionary<string, object> parameters)
    {
        this.Service = service;
        this.Method = method;
        this.Params = parameters;
    }
    public string Service;
    public string Method;
    public Dictionary<string, object> Params;
}
```

So if:
```C#
mc = new MethodCall(
   Service = "session",
   Method = "analystLogon",
   Params = new Dictionary<string, object>() {
       {"userId" : "username"},
       {"password": "password"}
};

Serialize.Xml(mc, x => x.UseCamelCaseNaming().MembersAsRootAttributes((t, o) => t.Name == "Service" || t.Name == "Method"));
```
I'm expecting to end up with something like:

```xml
<?xml version="1.0" encoding="UTF-8" />
<methodCall service="session" method="analystLogon">
    <params>
        <userId>username</userId>
        <password>password</password>
    </params>
</methodCall>
```

**Comment by mikeobrien** [comment]
Ok, perfect. I'll try to work something up right now.

**Comment by mikeobrien** [comment]
Actually now that I'm looking at this, would providing an alternative built in attribute do the trick? So you'd use it just as you would `XMLAttributeAttribute` but it would just be the Bender version. That would be *really* simple for me to add.

**Comment by MartiUK** [comment]
Yeah I tried something like that but didn't really work, up to you of course.

On 18 February 2016 14:56:44 GMT+00:00, mikeobrien <notifications@github.com> wrote:
>Actually now that I'm looking at this, would providing an alternative
>built in attribute do the trick? So you'd use it just as you would
>`XMLAttributeAttribute` but it would just be the Bender version. That
>would be *really* simple for me to add. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mikeobrien/Bender/issues/38#issuecomment-185756117

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mikeobrien** [comment]
You mean it didn't work because you don't want to use attributes (And want to use conventions instead) or you couldn't get it to work the way you wanted when you tried to configure it? Just wanna to make I'm understanding what you're looking for.

If the latter, I could mod it so this would produce the results you want:

```
public class MethodCall
{
    ...
    [Attribute]
    public string Service;
    [Attribute]
    public string Method;
    public Dictionary<string, object> Params;
}
```

Where `Bender.AttributeAttribute` (Or something along those lines) would work exactly as `XMLAttributeAttribute` does.

**Comment by MartiUK** [comment]
What I tried to say was I was looking at doing something similar, (writing my own xmlattributeattribute).

What you've outlined here is perfect.

**Comment by mikeobrien** [comment]
Ok, great, will add that right now, should be published in a few.

**Comment by MartiUK** [comment]
Thanks

**Comment by mikeobrien** [comment]
Aight, this is out there, you should be good to go. Let me know if you have any issues.

https://www.nuget.org/packages/Bender/
