### ISSUE TITLE
Deserializing xml from stream throws Root element is missing

### ISSUE THREAD

**Issue by nieve** [mikeobrien/Bender#39]
This fails:
``` csharp
var s = new FileStream(@"c:\\somefile.xml",FileMode.Open);
Bender.Deserialize.Xml<Foo>(s, Configure);
```

The ParseException is:
`
An exception of type 'Bender.ParseException' occurred in Bender.dll but was not handled in user code
Additional information: Root element is missing.
`

When passing in a stream created from a string, I get the same error; however, when passing in the string- it works.
Is it something to do with the stream position?

**Comment by mikeobrien** [comment]
Hrm, I have test coverage on that and its passing. Can you post the failing xml string? I'll if I can repro.

**Comment by nieve** [comment]
Ok, that was my bad- the deserialization was done inside a select statement and which was executed too late for the stream. Thanks for the prompt response though!

**Comment by mikeobrien** [comment]
Cool, glad you got it figured out.
