### ISSUE TITLE
Deserializing nested structures to flat objects?

### ISSUE THREAD

**Issue by nieve** [mikeobrien/Bender#40]
I'm working with a complex, highly nested xml file format, and would love to be able to just pick up some of the data and deserialize it into a smaller & concise flat object. 
Is it feasible, or even _desirable_, to play with the structure of the data when de/serializing data?
If not, is it something that can be implemented (wouldn't mind having a go at it if so)?

**Comment by mikeobrien** [comment]
Personally I'd use [Automapper](http://automapper.org/) to do this. Does exactly what you're talking about. Only downside is you'd have to deserialize it to an intermediary graph (Which I'm guessing is what you're trying to avoid). But it might be difficult to add that sort of thing to the serializer itself.

**Comment by nieve** [comment]
Yeah, I was hoping to avoid this. In fact, I'd much rather do the mapping manually, since the structure has so many multi-nested elements, that I'd need anyway to let AM know what to map and how. Would have been nice to have such a feature- _nice_ is the keyword... :wink:

**Comment by mikeobrien** [comment]
Only other thing I can think of is transforming it with XSLT. That could be something we could add easily, overload that takes both XML and XSLT, transforms it, then passes the transformed XML on to the serializer.

**Comment by nieve** [comment]
hmm, I'm definitely no XSLT expert - but would it be possible to serialize an "xslt object", just so that we could not deal with this beast? Or is that going too far? (I really cannot remember any of the xslt markup / structure).
The less I touch xml, the happier I am.

**Comment by mikeobrien** [comment]
Yeah I hear you about XML! XSLT can get pretty hairy and verbose (And it's awkward to pick up at first) but it is *the* DSL for transforming XML. It will take it from the complex source you mention to the flat version you want. Then that flat version could be deserialized. I think anything you do to try to avoid the XSLT would probably end up in reimplementing it to some degree so you might as well use it.

**Comment by nieve** [comment]
haha, got ya. Cool then- I think it's worth doing, esp. if it's not a lot of work. I could look into it, but if it'll be an easy thing for you, I'd be happy to weasel out of it.

**Comment by mikeobrien** [comment]
Yeah, I could add it, it's not a huge deal. I'll try to get it out there today.

**Comment by nieve** [comment]
![we re not worthy - imgur](https://cloud.githubusercontent.com/assets/202493/15049223/a9295ed2-12ed-11e6-9c9a-5fb02db6914b.gif)

**Comment by mikeobrien** [comment]
lol

**Comment by mikeobrien** [comment]
K, added this in, pushed it out to nuget. Here is how you use it.

```csharp
public const string Xml = "<Model><Fark>Hai</Fark></Model>";
public const string Xsl = @"<?xml version=""1.0"" encoding=""UTF-8""?>
        <xsl:stylesheet xmlns:xsl=""http://www.w3.org/1999/XSL/Transform"" version=""1.0"">
            <xsl:output method=""xml""/>

            <xsl:template match=""/Model"">
            <Model>
                <xsl:apply-templates select=""Fark""/>
            </Model>
            </xsl:template>

            <xsl:template match=""Fark"">
            <Oh>
                <xsl:value-of select=""."" />
            </Oh>
            </xsl:template>

        </xsl:stylesheet>";

public class Model
{
    public string Oh { get; set; }
}

var result = Deserialize.Xml<Model>(Xml, Xsl);
```

**Comment by nieve** [comment]
Beautiful! Really appreciate it!!!

**Comment by mikeobrien** [comment]
np, let me know if you have any issues!

**Comment by nieve** [comment]
Hey- works like a charm!! Plus it reduced my code significantly, so am all around happy :))

The less positive points are:
- only works with string xslt, no files (though it works for me since the xslt itself isn't too big and probably nicer to have nearby the end result class).
- Need to manually assign defaults with Readers for value types (since the structure is flat); unless I'm missing something?
- The friendly mapping exceptions tell me about the transformed xml, which is normal.

Last thing- and this is obviously way beyond the scope of Bender- ms xslt transformation exceptions are rather poor, and don't give straight forward information on what went wrong.

Many thanks for this feature, really makes a different!

**Comment by mikeobrien** [comment]
Awesome! Yeah, adding the file and stream overloads is pretty easy, I'll add them in. Not sure I understand the second point tho, if you can send me an example I'll look into it, sounds like something you shouldn't have to do. Yeah, friendly exceptions are a big deal, that's one of the big reasons I wrote this (Couldn't get it working in JSON.NET). I'll take a look and see if there is anything that can be done about that. It may be that Bender can catch those and parse them or something.

**Comment by nieve** [comment]
Rearding the first point- you don't need to bother, I'm happy with using the method taking in a string xslt, works better than a file.
The second point was, since I flatten the structure, I had to use a Reader to introduce default values if the conversion doesn't work (ie if the values are empty).
As for the friendly exception, I do get them, but they're referring to the *post*-xslt xml, not the oriinal one. Again, this is *normal*. I suppose it'll be a lot of work to provide friendly exceptions corresponding to the original xml.

**Comment by nieve** [comment]
Generally speaking, I'm not really asking for anything here, just though I'd give some feedback. And again, it's absolutely awesome :)

**Comment by mikeobrien** [comment]
Ok cool, thx! I'll def add the file and stream overloads tho, very low
hanging fruit.
