### ISSUE TITLE
Swith to .net Standard to also support .net Core and .net Standard projects

### ISSUE THREAD

**Issue by patrickweegen** [mikeobrien/Bender#43]
When using Bender in .net Core or .net Standard projects there will be an warning because Bender does not support .net Core at the Moment.

To be able to use Bender with .net Core you also have to add the package System.Data.SqlClient manually .

If Bender would be switched to .net Standard it could support .net Core, .net Standard and the .net Framework.

**Comment by mikeobrien** [comment]
Unfortunately I've stopped development/support for Bender. Between performance issues and the fact that pretty much everyone uses JSON.NET I've decided to put my efforts into other projects. I'll still accept PR's tho.
